spring:

  datasource:
    url: jdbc:h2:tcp://localhost/~/jwttutorial
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging.level:
    org.hibernate.SQL: debug
